name: cargo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mailer: ^5.0.0
  shared_preferences: ^2.3.2
#  country_code_picker: ^2.0.2
#  intl_phone_field: ^3.2.0
  bottom_sheet_bar: ^2.3.10
#  intl_phone_number_input: ^0.7.4
  image_picker: ^1.1.2
  http_parser: ^4.0.2
#  google_ml_kit: ^0.19.0
  excel: ^2.0.5
  permission_handler: ^11.3.1
  #  flutter_native_image: ^0.0.6+1
  path_provider: ^2.1.4
#  share_plus: ^6.3.1
#  flutter_tesseract_ocr: ^0.4.25
  image: ^4.3.0
#  web_socket_channel: ^3.0.1
#  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.1
  flutter_map:
  flutter_open_street_map: ^0.0.4
  google_maps_flutter: ^2.10.0
  webview_flutter: ^4.2.1
  #  socket_io_client: ^3.0.1
#  flutter_map: ^7.0.2
#  latlong2: ^0.9.1
#  flutter_svg:

  # State Management
  get:
  get_storage:

  # Network Manager
  connectivity_plus:
  http:
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/cargo_logo_app_icon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/cargo_logo_app_icon.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/cargo_logo_app_icon.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/cargo_logo_app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/urd.traineddata
    - assets/tessdata/ara.traineddata
    - assets/tessdata/OCRB.traineddata
    - assets/tessdata/financial.traineddata
    - assets/tessdata/eng.traineddata
    - assets/tessdata/pdf.ttf
    - assets/tessdata_config.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
